### PR TITLE
styling changes for the admin screen

### PR DESCRIPTION
**Pull request by tydolla00**

### CODE REVIEW

**Comment by tydolla00** [comment]
@Shargrove09 Let's use this branch to discuss changes to the ui.

**Comment by Shargrove09** [comment]
@tydolla00 Sounds good.  Let's make a plan to start inputting data so we can get a feel and more critiques for the admin form.

**Comment by tydolla00** [comment]
> @tydolla00 Sounds good. Let's make a plan to start inputting data so we can get a feel and more critiques for the admin form.

Well one of us gotta finish the form logic of the form (allow multiple stat names), I can start getting data tho. I'm away this weekend so prob late next week, I can start.

**Comment by Shargrove09** [comment]
> > @tydolla00 Sounds good. Let's make a plan to start inputting data so we can get a feel and more critiques for the admin form.
> 
> Well one of us gotta finish the form logic of the form (allow multiple stat names), I can start getting data tho. I'm away this weekend so prob late next week, I can start.

I can look at the form logic but I say we jus start with one game and get a bunch of data for that, we should make a spreadsheet of all the videos and track when we input them

**Comment by tydolla00** [comment]
merging until I think of the next thing I want to change.

**Pull request merged**
